openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
  /magic:
    post:
      tags:
        - magic-ball-controller
      operationId: magicAnswer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Answer'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Answer'
  /word:
    get:
      tags:
        - word-controller
      operationId: getRandomQuote
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Word'
  /quotes:
    get:
      tags:
        - quote-controller
      operationId: getRandomQuote_1
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Quote'
components:
  schemas:
    Answer:
      type: object
      properties:
        id:
          type: integer
          format: int32
        question:
          type: string
        answer:
          type: string
    Word:
      type: object
      properties:
        word:
          type: string
        definition:
          type: string
        id:
          type: integer
          format: int32
    Quote:
      type: object
      properties:
        quote:
          type: string
        author:
          type: string
        id:
          type: integer
          format: int32
